// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxM7gv77p4Ez86AEcrd5da41jmq_7ul8',
    appId: '1:738651067984:web:035aa14609c156ba202355',
    messagingSenderId: '738651067984',
    projectId: 'rg-mana',
    authDomain: 'rg-mana.firebaseapp.com',
    storageBucket: 'rg-mana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBbmgAFamPpcSib2_f5QLzqhPTETa3W8M',
    appId: '1:738651067984:android:07ea58f95af230bb202355',
    messagingSenderId: '738651067984',
    projectId: 'rg-mana',
    storageBucket: 'rg-mana.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByxM7gv77p4Ez86AEcrd5da41jmq_7ul8',
    appId: '1:738651067984:web:1311aa099450612c202355',
    messagingSenderId: '738651067984',
    projectId: 'rg-mana',
    authDomain: 'rg-mana.firebaseapp.com',
    storageBucket: 'rg-mana.firebasestorage.app',
  );
}
